name: Deploy to Railway

on:
  push:
    branches:
      - main  # Wdrażanie po pushu do `main`

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to Railway
        uses: railwayapp/cli-action@v2
        with:
          railway_api_token: ${{ secrets.RAILWAY_TOKEN }}
          service: your-service-name  # Opcjonalne, jeśli masz wiele usług