name: Send Email on Push to Test Branch

on:
  push:
    branches:
      - test

jobs:
  send_email:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Send Email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ssl0.ovh.net
          server_port: 465  # Port SMTP (587 dla TLS, 465 dla SSL)
          username: test@gieldagolebi.pl
          password: p2J8VWwQPy9jraa
          subject: "🚀 Nowy push do test branch!"
          to: "kleinszmidtj@gmail.com"  
          from: "JulkaK <test@gieldagolebi.pl>"
          body: |
            Nowy push do test branch!

            Commit: ${{ github.event.head_commit.message }}
            Autor: ${{ github.actor }}
            Repozytorium: ${{ github.repository }}
            Zobacz zmiany: https://github.com/${{ github.repository }}/commit/${{ github.sha }}
